# Power Consumption Model

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [7]:
# load the data
power_data = pd.read_csv('./Data/powerconsumption_cleaned.csv')
power_df = pd.DataFrame(power_data)

In [8]:
# Splitting the data
X = power_df[['Temperature', 'Humidity', 'WindSpeed', 'Hour']]
y = power_df['PowerClass']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# Training the model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Making predictions
y_pred_RFC = model.predict(X_test)

In [10]:
import joblib
# Save the model
joblib.dump(model, './models/power_consumption.pkl')
print("Model dumped!")

Model dumped!


In [11]:
print("RandomForestClassifier Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_RFC):.2f}")
print(f"Precision: {precision_score(y_test, y_pred_RFC, average='macro'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_RFC, average='macro'):.2f}")
print(f"F1-Score: {f1_score(y_test, y_pred_RFC, average='macro'):.2f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_RFC))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_RFC))

RandomForestClassifier Evaluation:
Accuracy: 0.92
Precision: 0.9161
Recall: 0.92
F1-Score: 0.92

Confusion Matrix:
[[3254   31  291]
 [   8 3268  179]
 [ 204  171 3078]]

Classification Report:
              precision    recall  f1-score   support

        High       0.94      0.91      0.92      3576
         Low       0.94      0.95      0.94      3455
    Moderate       0.87      0.89      0.88      3453

    accuracy                           0.92     10484
   macro avg       0.92      0.92      0.92     10484
weighted avg       0.92      0.92      0.92     10484



In [12]:
# Initialize and train the Logistic Regression model
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)

# Predict on the test data
y_pred_log_reg = log_reg.predict(X_test)

In [13]:
print("Logistic Regression Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log_reg):.2f}")
print(f"Precision: {precision_score(y_test, y_pred_log_reg, average='macro'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_log_reg, average='macro'):.2f}")
print(f"F1-Score: {f1_score(y_test, y_pred_log_reg, average='macro'):.2f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_log_reg))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_log_reg))

Logistic Regression Evaluation:
Accuracy: 0.72
Precision: 0.7081
Recall: 0.71
F1-Score: 0.71

Confusion Matrix:
[[2679  253  644]
 [  26 2999  430]
 [1056  577 1820]]

Classification Report:
              precision    recall  f1-score   support

        High       0.71      0.75      0.73      3576
         Low       0.78      0.87      0.82      3455
    Moderate       0.63      0.53      0.57      3453

    accuracy                           0.72     10484
   macro avg       0.71      0.71      0.71     10484
weighted avg       0.71      0.72      0.71     10484



In [14]:
# Initialize and train the KNN model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# Predict on the test data
y_pred_knn = knn.predict(X_test)

In [15]:
# Evaluate k-nn
print("Logistic Regression Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn):.2f}")
print(f"Precision: {precision_score(y_test, y_pred_knn, average='macro'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_knn, average='macro'):.2f}")
print(f"F1-Score: {f1_score(y_test, y_pred_knn, average='macro'):.2f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_knn))

Logistic Regression Evaluation:
Accuracy: 0.89
Precision: 0.8947
Recall: 0.89
F1-Score: 0.89

Confusion Matrix:
[[3222   44  310]
 [  22 3226  207]
 [ 281  237 2935]]

Classification Report:
              precision    recall  f1-score   support

        High       0.91      0.90      0.91      3576
         Low       0.92      0.93      0.93      3455
    Moderate       0.85      0.85      0.85      3453

    accuracy                           0.89     10484
   macro avg       0.89      0.89      0.89     10484
weighted avg       0.89      0.89      0.89     10484

